### ISSUE TITLE
error reading source directory: couldn't list files: Status 405 "405 Not Allowed"

### ISSUE THREAD

**Issue by jonntd** [wiserain/rclone#25]
cmd := exec.Command("rclone", "sync", sourceDir, filepath.Join(remoteDest, sourceDir[colonIndex+1:]), "--tpslimit", "2", "--update", "--fast-list", "--checkers", "2", "--log-level", "INFO", "--delete-after", "--size-only", "--ignore-times", "--ignore-existing", "--ignore-checksum", "--max-size", "10M", "--transfers", "2", "--multi-thread-streams", "2", "--local-encoding", "Slash,InvalidUtf8", "--115-encoding", "Slash,InvalidUtf8", "--exclude", "*.strm")

cmd := exec.Command("rclone", "lsf", "-R", sourceDir, "-vv", "--files-only", "--min-size", "100M", "--transfers", "2", "--multi-thread-streams", "2", "--local-encoding", "Slash,InvalidUtf8", "--115-encoding", "Slash,InvalidUtf8", "--tpslimit", "2")

有啥办法限制一下啊 一直405

**Comment by UVJkiNTQ** [comment]
--multi-thread-streams 0
-transfers 2
看看？

**Comment by jonntd** [comment]
> Try with `--tpslimit` smaller than or equal to 1.0?-----------谷歌翻译-----------尝试使用小于或等于 1.0 的 --tpslimit 吗？
改成 --tpslimit 0.5 可以了
